### ISSUE TITLE
Copyrighted image

### ISSUE THREAD

**Issue by reinerh** [d0c-s4vage/lookatme#107]
Hi,

I recently packaged [lookatme](https://packages.debian.org/sid/lookatme) for Debian, as I think it is a cool presentation tool. :-)
I wanted to update the package now to the current release, but noticed that you have included the file examples/napoleon_dynamite.jpg, which is not freely licensed.  
Could you please replace it with some picture under a free license? This would make packaging easier, as I could re-use your released tarballs, instead of repacking them (and removing the image).

**Comment by d0c-s4vage** [comment]
Gah, definitely! Thank you for bringing this up!

**Comment by d0c-s4vage** [comment]
In ~a minute v2.2.0 will land on pypi. Thanks again for bringing this up, and an especially large thank you for packaging it for debian!!

**Comment by d0c-s4vage** [comment]
Is there anything I can do on my end to make packaging or package maintenance easier?

**Comment by reinerh** [comment]
Thank you for fixing it so quickly!

I'm currently using the source tarball from Github for the package. This contains `{{VERSION}}` placeholders in a few files.
I just checked the tarball from pypi and noticed that it has been properly replaced there.
But on the other hand the pypi tarball is missing some files compared to the Github tarball, like docs/ and examples/. Because of that I'll keep using the Github tarball to provide documentation and examples in the package. But I'm also carrying a patch that replaces `{{VERSION}}` with the upstream version.
It would be a bit easier if either the placeholder is also replaced in the Github tarball, or if the pypi tarball had the same contents.
But it's also not a big deal, updating the version in the patch is done in a few seconds. :-)

**Comment by KarlWithK** [comment]
Hey I just wanted to note that I package lookatme for the AUR. I also packaged the extensions that I saw in this markdown. It was my first time, but I believe they all work. Anyway, I'm looking forward to seeing how this project progresses.
