### ISSUE TITLE
Embedded terminal not working

### ISSUE THREAD

**Issue by AckslD** [d0c-s4vage/lookatme#113]
**Describe the bug**

**To Reproduce**

1. Go to examples `cd examples/file_loader_ext`
2. Show the slide `lookatme example.md` 

**Expected behavior**
A embedded terminal as in the screencast in the README.

**Screenshots**
What I see is:

![gscreenshot_2021-04-18-123604](https://user-images.githubusercontent.com/23341710/115142556-b6cb6200-a042-11eb-8201-0e78de6a04e4.png)

**Environment (please complete the following information):**
 - OS: arch (5.11.14-arch1-1)
 - Lookatme Version: 2.3.0

**Additional context**
My first time trying out lookatme so not sure I missed something

**Comment by d0c-s4vage** [comment]
Thank you for reporting this!

I'll test this out on one of my Macs. There may be some platform-specific issues to work around - I'll dig into it.

**Comment by evanbattaglia** [comment]
I had to add

```
extensions:
  - terminal
```

to the presentation headers. Then it worked. I'm on Linux.

**Comment by pwntester** [comment]
> I had to add
> 
> ```
> extensions:
>   - terminal
> ```
> 
> to the presentation headers. Then it worked. I'm on Linux.

That worked for me on macos too, thanks!

**Comment by AckslD** [comment]
@evanbattaglia Thanks that worked :+1: also doing
```
lookatme -e terminal example.md
```
worked

**Comment by d0c-s4vage** [comment]
Ah, I misunderstood part of the issue. Glad it's working :^) I should probably update the documentation to make this clearer.

**Comment by d0c-s4vage** [comment]
I've created https://github.com/d0c-s4vage/lookatme/issues/121 to update the documentation and tutorial. Closing this issue.
