### ISSUE TITLE
Crashes over SSH (both in and out of tmux)

### ISSUE THREAD

**Issue by garwil** [d0c-s4vage/lookatme#122]
[lookatme.log](https://github.com/d0c-s4vage/lookatme/files/6681047/lookatme.log)
**Describe the bug**
Loading the second slide in the examples/tour.md document causes lookatme to crash with the following error:

```
Error rendering slide 2: 'DequeCommandTransmitter' object has no attribute 'transmitter'
See /tmp/lookatme.log for traceback
Aborted!
```
I get that it's probably really weird to be using this over SSH, but my work laptop's display output doesn't work with my KVM, so I tend to just SSH into it from my desktop. I've attached a log after running `lookatme --debug tour.md`

**To Reproduce**

1.  Connect to a remote host over SSH
2. `lookatme tour.md`

**Expected behavior**

Either the slideshow should run (which given the Ueberzug and Terminal extensions is probably unrealistic) , or should gracefully handle errors caused by being run over SSH.

**Environment (please complete the following information):**
 - OS: Arch Linux (btw)
 - Lookatme Version: 2.3.2 installed via pip

[lookatme.log](https://github.com/d0c-s4vage/lookatme/files/6681047/lookatme.log)

**Comment by chnoack** [comment]
I see this error also locally, if I use the extension "image_ueberzug"

**Comment by d0c-s4vage** [comment]
I think this could be described as lookatme needing better error handling in general when dealing with extensions. The terminal extension shouldn't be a problem, but I could definitely see the image_ueberzug causing problems.

**Comment by tommitah** [comment]
Same problem, I got this presentation that I'm supposed to do tomorrow... Weird how on my desktop (Void Linux) this still works but on my Arch laptop it doesn't.

**Comment by d0c-s4vage** [comment]
@tommitah are you using any extensions, or is it crashing with stock/plain lookatme?

**Comment by tommitah** [comment]
@d0c-s4vage My bad, was supposed to mention the image extension. Same setup as OP, except local.

It works without the extension, guess my presentation will be a tad more boring this time.

**Comment by d0c-s4vage** [comment]
Ah, yeah. The image extension uses ueberzug, which uses X11 to render/hide the image onto the the section of the screen so that it lines up with the terminal. Since it *is* X11, there's probably some way to get it working with X11 forwarding over SSH, but I haven't tried that yet.
