### ISSUE TITLE
Setting theme to "light" doesn't appear to do anything

### ISSUE THREAD

**Issue by Hubro** [d0c-s4vage/lookatme#123]
**Describe the bug**

Setting theme to light/dark with `-t light` and `-t dark` doesn't seem to have any effect.

**Screenshots**

`lookatme slides.md` with dark background terminal:

![image](https://user-images.githubusercontent.com/597206/124942318-cfc52d00-e00b-11eb-9b4b-fec34fad71cb.png)

`lookatme slides.md` with light background terminal:

![image](https://user-images.githubusercontent.com/597206/124942421-e66b8400-e00b-11eb-8863-f46f0dba4075.png)

`lookatme -t light slides.md` with light background terminal:

![image](https://user-images.githubusercontent.com/597206/124942519-ff743500-e00b-11eb-9f98-8d2e35223900.png)

It sounded from the help text like `-t light` should make the colors more readable on a light background, but it doesn't seem to have any effect.

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Lookatme Version: 2.3.2
 - Terminal: Alacritty

**Comment by d0c-s4vage** [comment]
Hmm, you're right. I wonder when this broke. Thank you for reporting this!

**Comment by d0c-s4vage** [comment]
Again, thanks for reporting this! I took a break from open source work for a while and am getting back to it. I'll get this fixed this week.

**Comment by yourealwaysbe** [comment]
It's something to do with [this line](https://github.com/d0c-s4vage/lookatme/blob/main/lookatme/pres.py#L109). If you comment it out, then the light theme comes into effect. It looks like that line overwrites the chosen command line theme.

**Comment by RoryNesbitt** [comment]
This issue seems to also effect `--style`. At least for me neither option changes how the presentation looks

**Comment by d0c-s4vage** [comment]
Taking a look!

**Comment by d0c-s4vage** [comment]
Works now with 2.4.1

```
pip install --upgrade lookatme
```

**Comment by RoryNesbitt** [comment]
Can confirm this has solved the `--theme` issue but `--style` still seems to do nothing for me

**Comment by d0c-s4vage** [comment]
Hmm, what if you do this - do you see the same changes? If you're not seeing the same things I'm seeing with `--style`, then yes, let's open another issue. (side note: I think the `--style` CLI argument should be renamed to `--code-style` or something, it's a bit non-intuitive).

test.md:
~~~markdown
# Hello

```python
def print_something():
    print("Something")
```
~~~

and then:

```bash
lookatme test.md
```
![image](https://user-images.githubusercontent.com/5090146/196190861-bb85b5a4-74c2-4b65-975f-536a98334389.png)

```bash
lookatme test.md --style zenburn
```
![image](https://user-images.githubusercontent.com/5090146/196190919-68021b35-06d8-4fca-9b8a-85e714666354.png)

```bash
lookatme test.md --style xcode
```
![image](https://user-images.githubusercontent.com/5090146/196190970-6da89475-3210-40d4-92f5-ab653c42a87e.png)

---

Or, you could quickly cycle through all of the supported code styles from pygments with this. It:
* lists all code styles that lookatme supports through pygments
* loops over each of them
* replaces the heading of `test.md` with the current style name in the loop
* then renders test.md with `--style <current-style>`

You'll have to press <kbd>q</kbd> to quit each time

```
for style in $(lookatme --help | grep -- --style | sed 's/^.*\[\(.*\)\]/\1/' | sed 's/|/ /g') ; do \
    sed -i "s/#.*/# $style/" test.md \
    lookatme test.md --style $style \
done
```
---
If you're not seeing what I'm seeing with this, then yes, let's open another issue!

**Comment by RoryNesbitt** [comment]
Yo this is my bad, you're entirely right this does work fine.
I've been trying to recolour the whole presentation not just the code blocks. (feature request I suppose, expanded `--theme` options)
