### ISSUE TITLE
Use Click v8

### ISSUE THREAD

**Issue by AmeerTaweel** [d0c-s4vage/lookatme#131]
I'm the maintainer of the `lookatme` package on [`nixpkgs`](https://github.com/NixOS/nixpkgs/pull/158323). The `nixpkgs` team is getting rid of Python 2, and they informed me that `lookatme` uses `Click v7`, which uses Python 2. I want to start working on updating `lookatme` to use `Click v8`, which is beneficial for `lookatme` users in general, not just the users on Nix.

I want to get approval before I start working on this.

**Comment by Kranzes** [comment]
In addition to that, it would also be nice if `lookatme` will be updated to use the latest PyYAML.
