### ISSUE TITLE
change colour of code block

### ISSUE THREAD

**Issue by gennaro-tedesco** [d0c-s4vage/lookatme#176]
Thank you for this awesome program!

More than a bug report a request for info/documentation: is it possible to change background colour of the default code blocks (and likewise, inline)? I have not been able to find the corresponding entry in the YAML [syntax](https://lookatme.readthedocs.io/en/latest/style_precendence.html#default-style-settings) (therefore I wonder if possible at all).

**Comment by d0c-s4vage** [comment]
Hi! You can't directly change the background of the code block, but you *can* change the syntax highlighting color scheme with either the command-line `--style` parameter, or the YAML `style:` key.

**Comment by d0c-s4vage** [comment]
E.g.

```
lookatme --style emacs your_slides.md
```

Or

~~~markdown
---
styles:
  style: emacs
---

```python
# a python codeblock
```
~~~

**Comment by gennaro-tedesco** [comment]
I will do so, thank you!
