### ISSUE TITLE
support kitty for image display

### ISSUE THREAD

**Issue by laoshaw** [d0c-s4vage/lookatme#205]
**Describe the Feature Request**

The ueberzug image is not working and its dependencies are not maintained and it's X11 only

**Example Markdown**

Any thing image in markdown, for kitty (icat) that can do image display, such as icat, viu, and mdcat

**Screenshot/Wireframe**
If applicable, add screenshots to help explain your proposed feature.

**Additional notes**
Add any other notes about the feature here.

**Comment by d0c-s4vage** [comment]
Ooh, I have an existing feature request (from myself) to get this implemented in lookatme v3.0 (#149). I haven't done much work on it yet, but I agree, this would be awesome to natively support.

Closing this as a duplicate - thank you for creating this issue!
