### ISSUE TITLE
Slides should be vertically scrollable

### ISSUE THREAD

**Issue by d0c-s4vage** [d0c-s4vage/lookatme#29]
I think all that needs to be done is use a ListBox instead of a Pile for the Frame body. This should let `pageup` and `pagedown` work.

This would also let users use lookatme to render markdown that was not intended to be viewed as slides in a presentation.

**Comment by d0c-s4vage** [comment]
Vertically scrollable slides should work and be turned on by default, as long as there's not any terminal instances inside of the source.

OR

Scrollable slides should be tried with all content, but if an error occurs while rendering, it makes the slide static and not scrollable.

I think I actually prefer the 2nd approach.

**Comment by huzecong** [comment]
Hi, may I ask what is the status on this issue? This tool is super awesome, and it would be really great if this vertical scrolling issue is resolved.

**Comment by d0c-s4vage** [comment]
fHi @huzecong ! I'm glad you like lookatme too! It's been a while since I checked on the state of urwid - it was stuck on some bugs around vertical scrolling not working correctly with urwid terminals.

**Comment by d0c-s4vage** [comment]
@huzecong turns out everything has cleared up with urwid - slides are now vertically scrollable in v1.3.0
