### ISSUE TITLE
Single Slide

### ISSUE THREAD

**Issue by lanox** [d0c-s4vage/lookatme#91]
Hi,

Sorry if this was something obvious but I couldn't find it in the documentation, is it possible to have a single slide only? 

I use it this when I write documentation in MD and sometimes having to scroll through all the slides is a bit annoying.

Thanks
lp

**Comment by d0c-s4vage** [comment]
Hi! Thanks for bringing this up!

Are you thinking of having a scrollable, single slide, or basically cat-ing the contents (rendered) to stdout?

**Comment by lanox** [comment]
Hi, 

Scrollable would be fine when required.

I guess my use case is similar to when you have instructions written up on how to do something, rather have multiple page like slides just to have a single page with scrolling.

**Comment by d0c-s4vage** [comment]
Gotcha, thanks for explaining! I may be able to get scrolling working soon - #29 was blocked for a really long time waiting for some changes to land in urwid. Those issues may have finally cleared up now in urwid's recent release. I'll keep this issue updated if it pans out!

**Comment by lanox** [comment]
Amazing thanks and amazing tool.

**Comment by d0c-s4vage** [comment]
Turns out, this is pretty much working now! Thank you for the prodding to double check. The blocked branch that was waiting on Urwid is now unblocked and will be merged in, and I'll add a cmd-line option to force a single, scrollable slide to be rendered

**Comment by d0c-s4vage** [comment]
I'm personally excited about this issue for the same reason - I use lookatme to view READMEs all the time too :^)

**Comment by lanox** [comment]
can't wait.

**Comment by d0c-s4vage** [comment]
Addressed with #29 and #96

**Comment by d0c-s4vage** [comment]
Landed in v1.3.0

```
pip install --upgrade lookatme
```

of if you use [pipx](https://github.com/pipxproject/pipx)

```
pipx upgrade lookatme
```
