### ISSUE TITLE
numbered lists don't seem to work

### ISSUE THREAD

**Issue by Incanus3** [d0c-s4vage/lookatme#93]
**Describe the bug**
numbered lists are rendered as bullet lists

**To Reproduce**

* create a md file with
```markdown
1. a
2. b
3. c
```
* run lookatme on it

**Expected behavior**
should render a numbered list

**Screenshots**
![Screenshot from 2020-09-19 12-55-13](https://user-images.githubusercontent.com/82725/93665528-6e7d9e80-fa77-11ea-8bb3-0193e7128476.png)

**Environment (please complete the following information):**
 - OS: Linux 5.8.6-1-MANJARO
 - Lookatme Version: 1.2.0

**Comment by d0c-s4vage** [comment]
Thanks for filing this bug! Should be an easy one to fix :^)

**Comment by d0c-s4vage** [comment]
Almost done - 
![image](https://user-images.githubusercontent.com/5090146/93668372-b2a17c80-fa40-11ea-9ed2-2b873a4758c1.png)

from

```markdown
* a list
* another list
    1. a nested numbered list
    1. should increment
        1. blah blah
        1. blah blah
            * hello again
            * hello again
            * hello again
            * hello again
```

**Comment by d0c-s4vage** [comment]
Fixed! Also fixed some general  list formatting inconsistencies

**Comment by Incanus3** [comment]
wow, that was fast. also a cool project, I saw it yesterday in [this talk](https://www.youtube.com/watch?v=EJqnWXDJZr0&list=PLcTu2VkAIIWzD2kicFNHN2c35XQCeZdsv) and thought I just have to have that. thanks for the great work.

**Comment by d0c-s4vage** [comment]
btw @Incanus3 thanks for pointing out that talk! I was wondering why it got so much attention recently

**Comment by Incanus3** [comment]
sure, glad to be of help.
